name: Bug Report
description: File a bug report
labels: ["bug"]
# assignees:
#   - komdog
body:
  - type: markdown
    attributes:
      value: |
        - When reporting bugs, you'll make our life simpler (and the fix will come sooner) if you follow the guidelines in this template.
        - Write a descriptive issue title above.
        - The golden rule is to always open one issue for one bug. If you notice several bugs and want to report them, make sure to create one new issue for each of them.
        - Search open and closed issues to ensure it has not already been reported. If you don't find a relevant match or if you're unsure, don't hesitate to open a new issue.
  - type: input
    id: contact
    attributes:
      label: Discord Tag
      description: |
        This is how we will contact you if we need more information.
      placeholder: ex. @yourname
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What OS are you using?
      options:
        - Windows
        - Linux
        - MacOS
        - Steam Deck (Linux)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 3.165 (Secret)
        - 3.15 (Beta)
        - 3.14 (Beta)
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell

